[window]
dimensions = { columns = 200, lines = 60 }
padding = { x = 8, y = 4 }
opacity = 0.8

[cursor]
style = "Beam"

[scrolling]
history = 100000
multiplier = 3

[font]
size = 15.0
offset = { x = 0, y = 2 }


[colors]
[colors.primary]
background = "#161821"
foreground = "#d2d4de"

[colors.normal]
black = "#161821"
red = "#e27878"
green = "#b4be82"
yellow = "#e2a478"
blue = "#84a0c6"
magenta = "#a093c7"
cyan = "#89b8c2"
white = "#c6c8d1"

[colors.bright]
black = "#6b7089"
red = "#e98989"
green = "#c0ca8e"
yellow = "#e9b189"
blue = "#91acd1"
magenta = "#ada0d3"
cyan = "#95c4ce"
white = "#d2d4de"
