approval_policy = "on-request"
approvals_reviewer = "auto_review"
sandbox_mode = "workspace-write"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
plan_mode_reasoning_effort = "xhigh"
service_tier = "default"
commit_attribution = "Co-authored-by: Codex <noreply@openai.com>"
developer_instructions = "When creating Git commits, always append `Co-authored-by: Codex <noreply@openai.com>` after one blank line."
# model_context_window = 1000000
# model_auto_compact_token_limit = 900000

[analytics]
enabled = false

[feedback]
enabled = false

[features]
multi_agent = true
prevent_idle_sleep = true
codex_git_commit = true
# default_mode_request_user_input = true

[notice]
hide_rate_limit_model_nudge = true

[tui]
status_line = [
    "model-with-reasoning",
    "context-remaining",
    "current-dir",
    "git-branch",
    "weekly-limit",
]
status_line_use_colors = true
notifications = true
notification_condition = "unfocused"

[sandbox_workspace_write]
web_search = "live"
