name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pkgs
        run: apt-get update && apt-get install -y git bash zsh vim
      - name: Install dotfiles
        run: git clone --recursive -j 8 https://github.com/th2ch-g/dotfiles.git
      - name: Show help message
        run: ./install.sh --help
        working-directory: dotfiles
      - name: Link all
        run: ./install.sh --link
        working-directory: dotfiles
      - name: Unlink dotfiles1
        run: ./install.sh --unlink
        working-directory: dotfiles
      - name: Link zsh
        run: ./install.sh --zsh
        working-directory: dotfiles
      - name: Unlink dotfiles2
        run: ./install.sh --unlink
        working-directory: dotfiles
      # skip vim
      # - name: Link vim
      #   run: ./install.sh --vim
        working-directory: dotfiles
      - name: Unlink dotfiles3
        run: ./install.sh --unlink
        working-directory: dotfiles
      - name: Link tmux
        run: ./install.sh --tmux
        working-directory: dotfiles
      - name: Unlink dotfiles4
        run: ./install.sh --unlink
        working-directory: dotfiles
      - name: Link git
        run: ./install.sh --git
        working-directory: dotfiles
      - name: Unlink dotfiles5
        run: ./install.sh --unlink
        working-directory: dotfiles
