name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pkgs
        run: apt-get update && apt-get install -y git bash zsh
      - name: Show help message
        run: ./install.sh --help
      - name: Link all
        run: ./install.sh --link
      - name: Unlink dotfiles1
        run: ./install.sh --unlink
      - name: Link zsh
        run: ./install.sh --zsh
      - name: Unlink dotfiles2
        run: ./install.sh --unlink
      - name: Link vim
        run: ./install.sh --vim
      - name: Unlink dotfiles3
        run: ./install.sh --unlink
      - name: Link tmux
        run: ./install.sh --tmux
      - name: Unlink dotfiles4
        run: ./install.sh --unlink
      - name: Link git
        run: ./install.sh --git
      - name: Unlink dotfiles5
        run: ./install.sh --unlink
