on:
  push:
    branches:
      - main

name: docker image push

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/dotfiles:latest --tag ghcr.io/$GITHUB_ACTOR/dotfiles:$(echo $GITHUB_SHA | head -c7) docker
      - name: push
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/dotfiles:latest
