name: release cd
on:
  push:
    tags:
      - "v*.*.*"
  # workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # create the GitHub Release
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Release
        uses: softprops/action-gh-release@v3 # zizmor: ignore[superfluous-actions]
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkout the repo
      packages: write # push to ghcr.io
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dotfiles:latest
            ghcr.io/${{ github.repository_owner }}/dotfiles:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
